load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary", "cc_test", "cc_import")

cc_library(
    name = "data_types",
    srcs = [
        "pair.cpp",
        "query.cpp",
        "text.cpp",
    ],
    hdrs = glob(["*.h"]),
    deps = [
        "//util",
        "//library/cpp/binsaver",
    ],
    visibility = ["//visibility:public"],
)
